import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <header>{/* Aquí podrías poner un logo o navegación global */}</header>
        <main id="main-content" tabIndex={-1}>
          {children}
        </main>
        <footer>{/* Aquí podrías poner información de contacto, links, etc. */}</footer>
      </body>
    </html>
  );
}
